# Use the latest 2.1 version of CircleCI pipeline process engine.
# See: https://circleci.com/docs/2.0/configuration-reference
version: 2.1

orbs:
  codecov: "codecov/codecov@3.2.2"

jobs:
  build-and-test:
    docker:
      - image: cimg/go:1.21
    steps:
      - checkout
      - run:
          name: "Build"
          command: |
            go install ./...
      - run:
          name: "Unit tests"
          command: |
            go test -race -covermode=atomic -coverprofile=coverage.out ./...
      - codecov/upload:
          file: coverage.out

workflows:
  build-and-test-workflow:
    jobs:
      - build-and-test
